name: "Test Post to PR"
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  units:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cat $GITHUB_EVENT_PATH
    - run: npm ci
    - run: npm test | tee unit_test_result.txt
    - name: "Post to PR"
      uses: ./
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        post_to_pr_definition: |
          [
            {
              "message_file": "./unit_test_result.txt",
              "title": "Unit Test",
              "modifier": "grep -v '::debug::'",
              "collapsible": true,
              "compare_branches": ["main"]
            }
          ]